services:
  mongodb:
    image: mongo:7.0.4
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    volumes:
      - mongo_data:/data/db

  inventory-db:
    image: mysql:8
    container_name: inventory-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: inventory-db
    volumes:
      - inventory_data:/var/lib/mysql

  order-db:
    image: postgres:16-alpine
    container_name: order-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: order_db
    volumes:
      - order_data:/var/lib/postgresql/data
  keycloak-db:
    image: postgres:16-alpine
    container_name: keycloak-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: keycloak_db
    volumes:
      - keycloak_data:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak-db
      KC_DB_USERNAME:
      KC_DB_PASSWORD:
      KEYCLOAK_ADMIN:
      KEYCLOAK_ADMIN_PASSWORD:
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
volumes:
  mongo_data:
  inventory_data:
  order_data:
  keycloak_data:
