services:
  # 1. El Servicio de Base de Datos
  mongodb:
    image: mongo:7.0.4
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME={user}
      - MONGO_INITDB_ROOT_PASSWORD={pass}
    volumes:
      - mongo_data:/data/db

  # 2. Nuestra Aplicación (Product Service)
  product-service:
    build: .
    container_name: product-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://{user}:{pass}@mongodb:27017/product-db?authSource=admin
    depends_on:
      - mongodb

volumes:
  mongo_data:
