spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_URL}
          username: ${GITHUB_USER}
          password: ${GITHUB_TOKEN}
          clone-on-start: true
          default-label: main
server:
  port: 8888
